spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5432/rankupdb
    username: rankupadmin
    password: rankupadmin
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
