spring:
  application:
    name: tzk-rank-up
  profiles:
    active: railway
  sql:
    init:
      schema-locations: classpath:schema.sql
server:
  servlet:
    context-path: /api
  error:
    include-message:
      always
